version: "3"
services:
  postgres:
    build:
      dockerfile: Dockerfile
      context: postgres
    env_file:
      - postgres/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    build:
      dockerfile: Dockerfile
      context: pgadmin
    env_file:
      - pgadmin/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
