version: "3"
services:
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./docker/postgres
    env_file:
      - ./docker/postgres/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    build:
      dockerfile: Dockerfile
      context: ./docker/pgadmin
    env_file:
      - ./docker/pgadmin/pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
